name: tleap
channels:
- defaults
- pytorch
dependencies:
- pytorch=1.7.1
- torchvision=0.8.2
- cudatoolkit=10.2.*
- pyyaml
- h5py
- scikit-image
- jupyter
- pandas
- numpy
- pip:
    - wandb
    - opencv-python
